Repository ComPWA/expertsystem, pull requests merged in 2020-08, with the labels that each got.

#145 ci!: fix check typing in tests
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  expertsystem/__init__.py
  setup.cfg
  tests/data/test_particle.py
  tests/state/conservation_rules/test_cparity.py
  tests/state/conservation_rules/test_gparity.py
  tests/state/conservation_rules/test_mass.py
  tests/state/conservation_rules/test_spin.py
  tests/state/test_particle.py
  tests/ui/test_systemcontrol.py
  tox.ini
Labels: :bulb: DX

#137 ci: add PR title check
  .github/workflows/pr-name.yml
  .gitignore
Labels: :bulb: DX, :clock1: Trivial, :warning: Low

#148 ci: fix missing commitlint config
  commitlint.config.js
  cspell.json
Labels: :bulb: DX, Bug

#147 feat: add type hints topology module
  expertsystem/data.py
  expertsystem/topology/graph.py
  expertsystem/topology/topology_builder.py
  setup.cfg
  tests/data/test_particle.py
Labels: :bulb: DX, :bulb: Enhancement

#135 feat: define quantum state interfaces
  .pylintrc
  .travis.yml
  README.md
  cspell.json
  doc/conf.py
  doc/index.rst
  environment.yml
  expertsystem/__init__.py
  expertsystem/data.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/__init__.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  pyproject.toml
  setup.cfg
  tests/data/test_particle.py
  tests/io/test_particle_collection.py
Labels: :bulb: Maintenance

#151 refactor!: replace DATABASE with ParticleColl
  examples/particles.ipynb
  examples/quickstart.ipynb
  expertsystem/data.py
  expertsystem/state/particle.py
  expertsystem/topology/graph.py
  expertsystem/ui/_default_settings.py
  setup.cfg
  tests/io/test_particle_collection.py
  tests/state/test_particle.py
Labels: :bulb: Docs, :bulb: Enhancement, :bulb: Maintenance

#153 refactor: use generic dataclass as QuantumState
  expertsystem/data.py
  expertsystem/io/xml/_build.py
  expertsystem/io/yaml/_build.py
  tests/data/test_particle.py
  tests/data/test_states.py
  tests/io/test_particle_collection.py
Labels: 🔨 Maintenance

#159 ci: import current GitHub issue labels
  labels.toml
  setup.cfg
Labels: 🖱️ DX

#160 ci: import new GitHub category labels
  .github/workflows/pr-linting.yml
  .github/workflows/pr-name.yml
  labels.toml
Labels: 🖱️ DX

#161 ci: migrate to GitHub workflow
  .github/workflows/ci.yml
  .github/workflows/pypi.yml
  .gitignore
  .travis.yml
  .vscode/settings.json
  README.md
  cspell.json
  doc/conf.py
  doc/index.rst
Labels: 🖱️ DX

#154 refactor: move recipe Magnitude and Phase up
  .github/workflows/ci.yml
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/schemas/yaml/amplitude-model.json
Labels: 💡 Enhancement

#162 ci: update contribute page
  README.md
  doc/contribute.rst
  doc/index.rst
Labels: 📝 Docs

#164 ci: increase minimal test coverage
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
  .pre-commit-config.yaml
  codecov.yml
  tests/channels/test_d0_to_kskpkm.py
  tox.ini
Labels: 🖱️ DX

#176 feat: add ComplexEnergyState adapter
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_dump.py
  tests/io/test_xml_adapters.py
Labels: 🔨 Maintenance

#180 feat: implement Parity/Spin.__neg__ operator
  expertsystem/data.py
  tests/data/test_particle.py
Labels: 💡 Enhancement

#183 feat: print overwrite warning ParticleCollection
  expertsystem/data.py
Labels: 💡 Enhancement

#184 test!: switch to branch coverage
  .gitignore
  .vscode/settings.json
  codecov.yml
  tox.ini
Labels: 🖱️ DX

#186 ci: implement markdownlint
  .github/workflows/ci.yml
  .markdownlint.json
  .vscode/extensions.json
  README.md
  doc/index.rst
Labels: 🖱️ DX

#181 feat: add Particle builder façades
  cspell.json
  examples/particles.ipynb
  examples/quickstart.ipynb
  expertsystem/state/particle.py
  tests/state/test_particle.py
Labels: 💡 Enhancement

#187 docs: categorize badges + add mypy badge
  README.md
  cspell.json
  doc/index.rst
  doc/mypy_badge.svg
Labels: 📝 Docs

#191 ci: remove mypy module ignores
  expertsystem/amplitude/abstract_generator.py
  expertsystem/state/particle.py
  setup.cfg
  tests/state/test_particle.py
Labels: 🖱️ DX

#192 test: validate expected_recipe.yml
  .markdownlint.json
  README.md
  expertsystem/amplitude/_yaml_adapter.py
  tests/amplitude/expected_recipe.yml
  tests/amplitude/test_yaml_helicity.py
  tests/io/test_internal_dict.py
Labels: 🖱️ DX

#193 fix!: distinguish isospin 0 and None
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  tests/amplitude/expected_recipe.yml
  tests/io/test_particle_collection.py
Labels: 💡 Enhancement

#201 feat: replace K0S/K0L with K0/K0bar
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  tests/channels/test_d0_to_kskpkm.py
  tests/channels/test_nbody_reactions.py
Labels: 💡 Enhancement

#202 fix!: update PDG values in particle_list
  .pre-commit-config.yaml
  cspell.json
  expertsystem/data.py
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  tests/amplitude/expected_recipe.yml
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/data/test_particle.py
  tests/io/test_particle_collection.py
  tests/state/conservation_rules/test_c_parity.py
  tests/state/conservation_rules/test_g_parity.py
  tests/state/test_particle.py
  tests/topology_builder/test_simple_state_builder.py
  tox.ini
Labels: Bug, 🔨 Maintenance

#208 test: implement fixtures for relevant tests
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/state/test_particle.py
Labels: 🖱️ DX

#204 ci: check numpy typing
  expertsystem/state/particle.py
  setup.cfg
Labels: 🖱️ DX

#214 ci: improve DX with Jupyter Lab
  cspell.json
  doc/contribute.rst
  examples/particles.ipynb
  setup.cfg
Labels: 📝 Docs, 🖱️ DX

#203 refactor: use tilde for antiparticles
  cspell.json
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  expertsystem/ui/_system_control.py
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/state/test_particle.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#217 refactor: use PDG names for particle names
  examples/particles.ipynb
  examples/quickstart.ipynb
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  expertsystem/ui/_system_control.py
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/expected_recipe.yml
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/data/test_particle.py
  tests/unit/io/test_particle_collection.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#215 test: verify YAML parameters and dynamics
  tests/unit/amplitude/expected_recipe.yml
  tests/unit/amplitude/test_yaml_helicity.py
  tox.ini
Labels: 🔨 Maintenance

#212 refactor!: move create_particle builders to data
  examples/particles.ipynb
  expertsystem/data.py
  expertsystem/state/particle.py
  tests/unit/data/test_particle.py
  tests/unit/io/test_particle_collection.py
  tests/unit/state/test_particle.py
Labels: 🔨 Maintenance

#218 test: split ParticleCollection tests io/data
  tests/unit/conftest.py
  tests/unit/data/test_particle.py
  tests/unit/data/test_particle_collection.py
  tests/unit/io/test_particle_list.py
Labels: 🔨 Maintenance

#222 docs!: add type hint links in API
  .readthedocs.yml
  doc/conf.py
  setup.cfg
Labels: Bug, 📝 Docs, 🖱️ DX

#220 refactor: share test solutions with fixture
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/conftest.py
Labels: 🖱️ DX

#190 feat: create ParticleCollection from PDG
  examples/particles.ipynb
  expertsystem/data.py
  expertsystem/io/__init__.py
  expertsystem/io/_pdg.py
  expertsystem/io/yaml/_dump.py
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  setup.cfg
  tests/unit/amplitude/expected_recipe.yml
  tests/unit/data/test_particle.py
  tests/unit/data/test_particle_collection.py
  tests/unit/io/test_pdg.py
Labels: 💡 Enhancement

#216 feat: add topology.graph.DotGenerator for visualization of the topology
  .github/workflows/ci.yml
  .gitignore
  cspell.json
  doc/conf.py
  doc/contribute.rst
  doc/usage.rst
  examples/visualization.ipynb
  expertsystem/io/__init__.py
  expertsystem/io/dot.py
  setup.cfg
  tests/unit/io/test_dot.py
  tox.ini
Labels: 💡 Enhancement

#188 feat: add type hints to ui module
  expertsystem/state/particle.py
  expertsystem/topology/graph.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_system_control.py
  setup.cfg
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/ui/test_system_control.py
Labels: 💡 Enhancement, 🖱️ DX

#227 fix!: remove faulty print statement
  expertsystem/ui/_system_control.py
Labels: Bug

#225 refactor!: remove particle_list.*ml
  .gitignore
  cspell.json
  expertsystem/additional_particle_definitions.yml
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  expertsystem/ui/_default_settings.py
  setup.cfg
  tests/unit/io/test_particle_list.py
  tests/unit/io/test_pdg.py
Labels: 🔨 Maintenance

#200 feat: check spin magnitude+projection consistency
  expertsystem/data.py
  expertsystem/state/conservation_rules.py
  expertsystem/state/particle.py
  tests/unit/data/test_states.py
  tests/unit/state/conservation_rules/test_c_parity.py
Labels: 💡 Enhancement

#229 refactor!: merge topology submodules
  examples/quickstart.ipynb
  expertsystem/amplitude/abstract_generator.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/io/dot.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/topology.py
  expertsystem/topology/__init__.py
  expertsystem/topology/graph.py
  expertsystem/topology/topology_builder.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_system_control.py
  setup.cfg
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/unit/topology/test_simple_state_builder.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#230 feat: add type hints state.particle module
  .pre-commit-config.yaml
  expertsystem/state/particle.py
  setup.cfg
Labels: 🔨 Maintenance

#233 test: reorganize J/psi to gamma pi0 pi0
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
Labels: 🔨 Maintenance

#194 refactor!: change Rule interface to decorator
  expertsystem/state/conservation_rules.py
  expertsystem/state/propagation.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  tests/unit/state/conservation_rules/test_additive_qn.py
  tests/unit/state/conservation_rules/test_c_parity.py
  tests/unit/state/conservation_rules/test_g_parity.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/state/conservation_rules/test_mass.py
  tests/unit/state/conservation_rules/test_spin.py
  tox.ini
Labels: 🔨 Maintenance

#235 feat: visualize list of StateTransitionGraphs
  .gitignore
  .vscode/extensions.json
  examples/visualization.ipynb
  expertsystem/io/dot.py
  expertsystem/state/particle.py
  tests/unit/io/test_dot.py
  tests/unit/topology/test_graph.py
Labels: 💡 Enhancement, 🔨 Maintenance

#236 refactor!: remove particle DATABASE global
  examples/particles.ipynb
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/ui/__init__.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/conftest.py
  tests/unit/conftest.py
  tests/unit/data/test_particle_collection.py
  tests/unit/io/test_particle_list.py
  tests/unit/topology/test_graph.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#238 ci: automate release notes
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .gitignore
Labels: 🖱️ DX

#239 ci: improve order of release notes
  .github/release-drafter.yml
Labels: 🖱️ DX

#240 ci: fix $CONTRIBUTORS in release drafter
  .github/release-drafter.yml
Labels: Bug, 🖱️ DX

#241 build: downgrade to numpy 1.18.0
  setup.cfg
Labels: Bug

#242 docs: add GPLv3+ badge
  README.md
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  setup.cfg
Labels: 📝 Docs, 🖱️ DX
