Repository ComPWA/expertsystem, pull requests merged in 2020-12, with the labels that each got.

#401 refactor!: make solving module graph independent
  cspell.json
  docs/conf.py
  docs/usage/workflow.ipynb
  src/expertsystem/amplitude/__init__.py
  src/expertsystem/amplitude/canonical_decay.py
  src/expertsystem/amplitude/helicity_decay.py
  src/expertsystem/io/_dot.py
  src/expertsystem/io/_yaml/_dump.py
  src/expertsystem/reaction/__init__.py
  src/expertsystem/reaction/_system_control.py
  src/expertsystem/reaction/argument_handling.py
  src/expertsystem/reaction/combinatorics.py
  src/expertsystem/reaction/default_settings.py
  src/expertsystem/reaction/solving.py
  src/expertsystem/reaction/topology.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/conftest.py
  tests/unit/io/test_dot.py
  tests/unit/reaction/test_combinatorics.py
  tests/unit/reaction/test_solving.py
  tests/unit/reaction/test_system_control.py
  tests/unit/reaction/test_topology.py
Labels: 🔨 Maintenance

#405 fix: retrieve prefactor correctly from yaml file
  src/expertsystem/io/_yaml/_build.py
Labels: Bug

#406 feat: reduce edge qn domains to allowed states
  .github/workflows/ci.yml
  src/expertsystem/reaction/__init__.py
  src/expertsystem/reaction/solving.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
Labels: Bug, 💡 Enhancement

#407 ci: temporarily disable tests for mac os in CD
  .github/workflows/cd.yml
Labels: 🖱️ DX

#408 ci: enable mac os workflows again
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 🖱️ DX

#412 ci: update requirements through GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
  .github/workflows/requirements-cron.yml
  .github/workflows/requirements-pr.yml
  .gitpod.yml
  .readthedocs.yml
  .reqs/dev.in
  .reqs/doc.txt
  .reqs/sty.txt
  .reqs/test.txt
  .vscode/settings.json
  cspell.json
  docs/install.md
  environment.yml
  reqs/.gitignore
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  reqs/extract_install_requires.py
  reqs/requirements-dev.in
  reqs/requirements-doc.in
  reqs/requirements-sty.in
  reqs/requirements-test.in
  reqs/upgrade.sh
  requirements-dev.txt
  requirements.txt
  setup.cfg
  tox.ini
Labels: 🖱️ DX

#413 ci: remove pip-compile annotations dev
  reqs/3.6/requirements-dev.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.8/requirements-dev.txt
  reqs/upgrade.sh
Labels: Bug, 🖱️ DX

#414 ci: upgrade developer dependencies
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
  .github/workflows/pr-linting.yml
  .github/workflows/release-drafter.yml
  .github/workflows/requirements-cron.yml
  .github/workflows/requirements-pr.yml
  docs/conf.py
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  src/expertsystem/reaction/topology.py
Labels: 🔨 Maintenance, 🖱️ DX

#415 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
Labels: 🔨 Maintenance, 🖱️ DX
