Repository ComPWA/expertsystem, pull requests merged in 2020-10, with the labels that each got.

#284 refactor: use Particle in graph type of Solver interface
  expertsystem/nested_dicts.py
  expertsystem/solving/__init__.py
  expertsystem/ui/__init__.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#275 docs: improve docstring of Rule
  expertsystem/solving/conservation_rules.py
Labels: 📝 Docs

#289 ci: ignore draft pull requests
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
Labels: 🖱️ DX

#290 ci: add GitPod configuration
  .github/workflows/ci.yml
  .gitignore
  .gitpod.yml
  .vscode/.gitignore
  README.md
  cspell.json
  doc/index.rst
Labels: 🖱️ DX

#286 refactor!: move amplitude writers to io
  .github/workflows/linkcheck.yml
  expertsystem/amplitude/abstract_generator.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/yaml/__init__.py
  expertsystem/io/yaml/_dump.py
  expertsystem/io/yaml/_xml_to_yaml.py
  expertsystem/nested_dicts.py
  expertsystem/ui/__init__.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/conftest.py
Labels: 🔨 Maintenance

#287 feat!: implement AmplitudeModel class
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
  .pylintrc
  doc/conf.py
  examples/quickstart.ipynb
  expertsystem/amplitude/__init__.py
  expertsystem/amplitude/abstract_generator.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/amplitude/model.py
  expertsystem/data.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/__init__.py
  expertsystem/io/yaml/_dump.py
  expertsystem/io/yaml/_xml_to_yaml.py
  expertsystem/schemas/xml/particle-list.json
  expertsystem/ui/__init__.py
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/expected_recipe.yml
  tests/unit/amplitude/test_model.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/conftest.py
Labels: 🔨 Maintenance

#291 feat!: implement load_amplitude_model
  .pylintrc
  examples/quickstart.ipynb
  expertsystem/amplitude/model.py
  expertsystem/io/__init__.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/__init__.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  tests/unit/amplitude/test_io.py
Labels: 💡 Enhancement

#285 refactor!: change solutions type of Result class
  expertsystem/amplitude/canonical_decay.py
  expertsystem/data.py
  expertsystem/nested_dicts.py
  expertsystem/solving/__init__.py
  expertsystem/state/properties.py
  expertsystem/ui/__init__.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#296 fix: make expertsystem PEP-561 compatible
  expertsystem/py.typed
  setup.cfg
Labels: Bug

#295 feat: ignore name and pid in Particle comparison
  expertsystem/data.py
  expertsystem/io/_pdg.py
  tests/unit/io/test_particle_list.py
  tests/unit/io/test_pdg.py
  tests/unit/test_data.py
Labels: 🔨 Maintenance

#297 refactor!: fully abolish old nested dict graph in STM
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/data.py
  expertsystem/io/dot.py
  expertsystem/nested_dicts.py
  expertsystem/solving/__init__.py
  expertsystem/state/properties.py
  expertsystem/topology.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_system_control.py
  tests/channels/test_d0_to_ks_kp_km.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#298 chore: remove obsolete QNConverters
  expertsystem/nested_dicts.py
Labels: 🔨 Maintenance

#292 refactor: change ParticleCollection into set
  expertsystem/data.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/_dump.py
  expertsystem/solving/__init__.py
  expertsystem/state/properties.py
  expertsystem/ui/__init__.py
  tests/unit/io/test_particle_list.py
  tests/unit/io/test_pdg.py
  tests/unit/test_data.py
Labels: 💡 Enhancement, 🔨 Maintenance

#299 feat: implement Particle.__neg__ operator
  doc/interactive.rst
  expertsystem/data.py
  tests/unit/test_data.py
Labels: 💡 Enhancement

#300 fix: remove doctest directive
  .pre-commit-config.yaml
  cspell.json
  expertsystem/data.py
  tox.ini
Labels: 📝 Docs, 🖱️ DX

#301 refactor!: eliminate remaining nested dicts usage
  expertsystem/nested_dicts.py
  expertsystem/solving/__init__.py
  expertsystem/solving/conservation_rules.py
  expertsystem/state/properties.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/state/conservation_rules/test_spin.py
  tox.ini
Labels: Bug, 🔨 Maintenance

#307 style!: enforce isort sorting
  .pre-commit-config.yaml
  .vscode/settings.json
  README.md
  cspell.json
  doc/conf.py
  doc/index.rst
  expertsystem/__init__.py
  expertsystem/amplitude/__init__.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/io/__init__.py
  expertsystem/io/_pdg.py
  expertsystem/io/dot.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/xml/validation.py
  expertsystem/io/yaml/__init__.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  expertsystem/io/yaml/validation.py
  expertsystem/solving/__init__.py
  expertsystem/solving/conservation_rules.py
  expertsystem/state/__init__.py
  expertsystem/state/combinatorics.py
  expertsystem/state/properties.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  pyproject.toml
  setup.cfg
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/conftest.py
  tests/unit/io/test_dot.py
  tests/unit/io/test_particle_list.py
  tests/unit/io/test_pdg.py
  tests/unit/io/test_xml_adapters.py
  tests/unit/state/conservation_rules/test_c_parity.py
  tests/unit/state/conservation_rules/test_g_parity.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/state/conservation_rules/test_mass.py
  tests/unit/state/conservation_rules/test_spin.py
  tests/unit/ui/test_system_control.py
Labels: 🖱️ DX

#304 docs: add PyPI project URLs
  setup.cfg
Labels: 📝 Docs

#308 chore: remove numpy as a dependency
  cspell.json
  doc/conf.py
  expertsystem/_utils.py
  expertsystem/io/_pdg.py
  expertsystem/solving/conservation_rules.py
  expertsystem/state/combinatorics.py
  setup.cfg
Labels: 🔨 Maintenance

#312 refactor!: replace dataclasses with attrs
  .github/workflows/ci.yml
  doc/conf.py
  environment.yml
  expertsystem/__init__.py
  expertsystem/amplitude/model.py
  expertsystem/data.py
  expertsystem/solving/__init__.py
  expertsystem/solving/conservation_rules.py
  expertsystem/topology.py
  pyproject.toml
  setup.cfg
  tests/unit/test_data.py
Labels: 💡 Enhancement, 🔨 Maintenance

#313 refactor!: remove nested dict graph node props
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/data.py
  expertsystem/solving/__init__.py
  expertsystem/state/properties.py
  expertsystem/topology.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_system_control.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#315 fix: avoid deep copies of graphs during solving
  expertsystem/solving/__init__.py
  expertsystem/topology.py
Labels: 💡 Enhancement

#314 refactor!: reorganise submodules
  doc/contribute.rst
  examples/particles.ipynb
  expertsystem/__init__.py
  expertsystem/_utils.py
  expertsystem/amplitude/__init__.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/amplitude/model.py
  expertsystem/io/__init__.py
  expertsystem/io/_pdg.py
  expertsystem/io/dot.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/xml/validation.py
  expertsystem/io/yaml/__init__.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  expertsystem/io/yaml/validation.py
  expertsystem/particle.py
  expertsystem/reaction/__init__.py
  expertsystem/reaction/combinatorics.py
  expertsystem/reaction/conservation_rules.py
  expertsystem/reaction/quantum_numbers.py
  expertsystem/reaction/solving.py
  expertsystem/reaction/topology.py
  expertsystem/state/__init__.py
  expertsystem/state/properties.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  pyproject.toml
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/conftest.py
  tests/unit/amplitude/test_model.py
  tests/unit/io/test_dot.py
  tests/unit/io/test_particle_list.py
  tests/unit/io/test_pdg.py
  tests/unit/io/test_xml_adapters.py
  tests/unit/reaction/__init__.py
  tests/unit/reaction/conservation_rules/__init__.py
  tests/unit/reaction/conservation_rules/test_additive_qn.py
  tests/unit/reaction/conservation_rules/test_c_parity.py
  tests/unit/reaction/conservation_rules/test_g_parity.py
  tests/unit/reaction/conservation_rules/test_ls_coupling.py
  tests/unit/reaction/conservation_rules/test_mass.py
  tests/unit/reaction/conservation_rules/test_spin.py
  tests/unit/reaction/test_combinatorics.py
  tests/unit/reaction/test_topology.py
  tests/unit/test_particles.py
  tests/unit/ui/test_system_control.py
Labels: 📝 Docs, 🔨 Maintenance

#317 ci: report and clean up unused code
  expertsystem/reaction/conservation_rules.py
  expertsystem/ui/_system_control.py
  pyrightconfig.json
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/reaction/conservation_rules/test_ls_coupling.py
  tests/unit/reaction/conservation_rules/test_spin.py
Labels: 🔨 Maintenance, 🖱️ DX

#318 refactor: simplify API
  cspell.json
  doc/_templates/package.rst_t
  doc/api.rst
  doc/conf.py
  doc/usage.rst
  examples/particles.ipynb
  examples/visualization.ipynb
  expertsystem/__init__.py
  expertsystem/amplitude/__init__.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/io/__init__.py
  expertsystem/io/_dot.py
  expertsystem/io/_pdg.py
  expertsystem/io/_xml/__init__.py
  expertsystem/io/_xml/_build.py
  expertsystem/io/_xml/_dump.py
  expertsystem/io/_xml/validation.py
  expertsystem/io/_yaml/__init__.py
  expertsystem/io/_yaml/_build.py
  expertsystem/io/_yaml/_dump.py
  expertsystem/io/_yaml/validation.py
  expertsystem/particle.py
  expertsystem/reaction/__init__.py
  expertsystem/reaction/combinatorics.py
  expertsystem/reaction/conservation_rules.py
  expertsystem/reaction/solving.py
  expertsystem/reaction/topology.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  setup.cfg
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/io/test_dot.py
  tests/unit/io/test_xml.py
  tests/unit/reaction/test_combinatorics.py
  tox.ini
Labels: 📝 Docs, 🔨 Maintenance

#322 ci: activate flake8 bugbear
  expertsystem/reaction/conservation_rules.py
  expertsystem/reaction/solving.py
  expertsystem/ui/__init__.py
  setup.cfg
  tests/unit/reaction/conservation_rules/test_spin.py
  tox.ini
Labels: 🖱️ DX

#320 fix: validate list-only in recoil systems
  expertsystem/schemas/yaml/amplitude-model.json
Labels: Bug

#324 docs: visualize module dependencies
  cspell.json
  doc/.gitignore
  doc/conf.py
  doc/index.rst
  setup.cfg
Labels: 📝 Docs

#323 fix: remove conda-forge channel
  environment.yml
Labels: Bug

#327 feat: implement ParticleCollection.names
  doc/interactive.rst
  examples/particles.ipynb
  examples/quickstart.ipynb
  expertsystem/particle.py
  tests/unit/test_particles.py
Labels: Bug, 💡 Enhancement

#326 refactor!: merge ui into reaction and amplitude
  doc/conf.py
  doc/index.rst
  examples/particles.ipynb
  examples/quickstart.ipynb
  examples/visualization.ipynb
  expertsystem/__init__.py
  expertsystem/amplitude/__init__.py
  expertsystem/io/_xml/__init__.py
  expertsystem/io/_yaml/__init__.py
  expertsystem/reaction/__init__.py
  expertsystem/reaction/_default_settings.py
  expertsystem/reaction/_system_control.py
  expertsystem/reaction/solving.py
  expertsystem/ui/__init__.py
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/conftest.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/conftest.py
  tests/unit/reaction/test_system_control.py
  tests/unit/test_reaction.py
  tests/unit/ui/__init__.py
Labels: 🔨 Maintenance

#329 fix!: allow only EM on nodes with gamma
  expertsystem/reaction/_system_control.py
  tests/channels/test_nbody_reactions.py
Labels: Bug

#328 feat: move getter methods to Result
  examples/quickstart.ipynb
  expertsystem/amplitude/__init__.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/reaction/__init__.py
  expertsystem/reaction/solving.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/conftest.py
  tests/unit/io/test_dot.py
  tests/unit/reaction/test_solving.py
  tests/unit/test_reaction.py
Labels: 💡 Enhancement, 🔨 Maintenance

#330 fix: typo warning message existing PID
  expertsystem/particle.py
Labels: Bug

#332 fix: repair PreFactor key in YAML validation
  expertsystem/schemas/yaml/amplitude-model.json
Labels: Bug

#334 feat: raise exception no intermediate particles
  expertsystem/reaction/__init__.py
  tests/unit/test_reaction.py
Labels: 💡 Enhancement

#331 refactor!: improve Rule argument handling code
  .gitignore
  cspell.json
  doc/conf.py
  expertsystem/reaction/_default_settings.py
  expertsystem/reaction/argument_handling.py
  expertsystem/reaction/conservation_rules.py
  expertsystem/reaction/quantum_numbers.py
  expertsystem/reaction/solving.py
  pyproject.toml
  setup.cfg
  tests/channels/test_nbody_reactions.py
  tests/unit/reaction/conservation_rules/test_additive_qn.py
  tests/unit/reaction/conservation_rules/test_c_parity.py
  tests/unit/reaction/conservation_rules/test_g_parity.py
  tests/unit/reaction/conservation_rules/test_spin.py
Labels: 🔨 Maintenance

#340 fix: sort ParticleColl. getitem candidates by mass
  expertsystem/particle.py
  tests/unit/test_particles.py
Labels: 💡 Enhancement

#346 fix: move examples to doc/usage
  README.md
  doc/.gitignore
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  doc/usage/additional_particles.yml
  doc/usage/particles.ipynb
  doc/usage/quickstart.ipynb
  doc/usage/visualization.ipynb
  setup.cfg
Labels: Bug, 🔨 Maintenance

#348 fix: replace progress bar with tqdm
  cspell.json
  expertsystem/reaction/__init__.py
  setup.cfg
  tox.ini
Labels: 💡 Enhancement

#339 feat: automatically determine number of cores
  expertsystem/reaction/__init__.py
Labels: 🔨 Maintenance

#336 feat: implement Result.get_particle_graphs
  .vscode/settings.json
  doc/usage/quickstart.ipynb
  doc/usage/visualization.ipynb
  expertsystem/io/__init__.py
  expertsystem/io/_dot.py
  expertsystem/reaction/solving.py
  expertsystem/reaction/topology.py
  tests/unit/io/test_dot.py
  tests/unit/reaction/test_solving.py
Labels: 💡 Enhancement

#341 feat: visualize collapsed graphs
  doc/usage/visualization.ipynb
  expertsystem/io/_dot.py
  expertsystem/reaction/solving.py
  tests/unit/io/test_dot.py
  tests/unit/reaction/test_solving.py
Labels: 💡 Enhancement, 📝 Docs

#350 docs: hide logs from example pages
  cspell.json
  doc/usage/particles.ipynb
  doc/usage/quickstart.ipynb
  doc/usage/visualization.ipynb
Labels: 📝 Docs

#274 feat!: provide main facade functions
  cspell.json
  doc/interactive.rst
  doc/usage.ipynb
  doc/usage.rst
  doc/usage/particles.ipynb
  doc/usage/visualization.ipynb
  doc/usage/workflow.ipynb
  expertsystem/__init__.py
  expertsystem/amplitude/__init__.py
  expertsystem/reaction/__init__.py
  setup.cfg
  tests/channels/test_d0_to_ks_kp_km.py
  tests/unit/conftest.py
  tests/unit/test_reaction.py
Labels: 📝 Docs

#351 docs: upgrade to Sphinx Book Theme 0.0.38
  README.md
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  doc/interactive.rst
  doc/usage.ipynb
  doc/usage/particles.ipynb
  doc/usage/visualization.ipynb
  doc/usage/workflow.ipynb
  environment.yml
  expertsystem/__init__.py
  setup.cfg
Labels: Bug

#353 fix: correctly set facade docstrings
  .pre-commit-config.yaml
  doc/usage/particles.ipynb
  doc/usage/workflow.ipynb
  expertsystem/__init__.py
Labels: Bug, 📝 Docs

#354 ci: run Y → DDππ in master branch
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
Labels: 🖱️ DX

#357 test: write test output to subfolder
  cspell.json
  test/channels/test_d0_to_ks_kp_km.py
  test/conftest.py
  test/output/.gitkeep
  test/unit/amplitude/test_io.py
  test/unit/amplitude/test_parity_prefactor.py
  test/unit/amplitude/test_yaml_canonical.py
  test/unit/amplitude/test_yaml_helicity.py
  test/unit/io/test_dot.py
  test/unit/io/test_particle_list.py
Labels: 🖱️ DX
