Repository ComPWA/expertsystem, pull requests merged in 2020-09, with the labels that each got.

#243 refactor!: move particle combinatorics
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/state/particle.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_system_control.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#244 refactor!: remove QuantumState classes
  examples/particles.ipynb
  expertsystem/data.py
  expertsystem/io/_pdg.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  expertsystem/state/particle.py
  tests/unit/data/test_particle.py
  tests/unit/data/test_particle_collection.py
  tests/unit/data/test_states.py
  tests/unit/io/test_pdg.py
  tests/unit/io/test_xml_adapters.py
Labels: 🔨 Maintenance

#246 chore: implement some smaller fixes
  expertsystem/state/particle.py
  expertsystem/topology.py
  expertsystem/ui/__init__.py
  tests/unit/topology/test_graph.py
Labels: 🔨 Maintenance

#247 ci: implement pyright and VSCode Pylance
  .github/workflows/ci.yml
  .vscode/extensions.json
  .vscode/settings.json
  codecov.yml
  cspell.json
  expertsystem/data.py
  expertsystem/io/_pdg.py
  pyrightconfig.json
Labels: 🖱️ DX

#249 ci!: add cspell and markdownlint to tox
  cspell.json
  doc/contribute.rst
  tox.ini
Labels: 🖱️ DX

#248 refactor: extract Topology class
  .pylintrc
  expertsystem/state/particle.py
  expertsystem/topology.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_system_control.py
  tests/unit/topology/test_graph.py
  tests/unit/ui/test_system_control.py
  tox.ini
Labels: 💡 Enhancement, 🔨 Maintenance

#250 feat: implement Topology.verify and clean up
  .pylintrc
  .vscode/settings.json
  cspell.json
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/io/dot.py
  expertsystem/state/propagation.py
  expertsystem/topology.py
  expertsystem/ui/__init__.py
  tests/unit/io/test_dot.py
  tests/unit/state/test_graph_combinatorics.py
  tests/unit/test_topology.py
  tests/unit/topology/__init__.py
  tests/unit/topology/test_graph.py
  tests/unit/topology/test_simple_state_builder.py
Labels: 💡 Enhancement

#245 refactor!: improve graph combinatorics
  expertsystem/state/particle.py
  expertsystem/ui/__init__.py
  tests/unit/state/test_graph_combinatorics.py
  tests/unit/ui/test_system_control.py
Labels: 💡 Enhancement, 🔨 Maintenance

#253 refactor!: change conservation rule interface
  .pylintrc
  cspell.json
  doc/conf.py
  expertsystem/data.py
  expertsystem/state/conservation_rules.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  setup.cfg
  tests/channels/test_nbody_reactions.py
  tests/unit/state/conservation_rules/test_additive_qn.py
  tests/unit/state/conservation_rules/test_c_parity.py
  tests/unit/state/conservation_rules/test_g_parity.py
  tests/unit/state/conservation_rules/test_mass.py
  tests/unit/state/conservation_rules/test_spin.py
Labels: 🔨 Maintenance

#252 style: upgrade and apply black and prettier
  .pre-commit-config.yaml
  doc/_templates/genindex.html
  expertsystem/amplitude/helicity_decay.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/validation.py
  expertsystem/state/conservation_rules.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  setup.cfg
  tests/channels/test_nbody_reactions.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/data/test_particle.py
  tests/unit/data/test_states.py
  tests/unit/io/test_dot.py
  tests/unit/state/conservation_rules/test_additive_qn.py
  tests/unit/state/conservation_rules/test_g_parity.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/state/test_graph_combinatorics.py
  tests/unit/ui/test_system_control.py
Labels: 🖱️ DX

#251 docs!: switch to Sphinx Book theme
  README.md
  doc/adr/0000-use-markdown-architectural-decision-records.md
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  examples/particles.ipynb
  examples/quickstart.ipynb
  examples/visualization.ipynb
  setup.cfg
Labels: 📝 Docs

#260 feat: implement ParticleCollection.filter
  .github/workflows/ci.yml
  cspell.json
  doc/conf.py
  examples/particles.ipynb
  expertsystem/data.py
  expertsystem/state/particle.py
  setup.cfg
  tests/unit/data/test_particle.py
  tests/unit/data/test_particle_collection.py
  tests/unit/io/test_particle_list.py
  tests/unit/io/test_pdg.py
  tox.ini
Labels: 💡 Enhancement

#261 feat: add Particle.is_lepton method
  .vscode/settings.json
  doc/contribute.rst
  examples/particles.ipynb
  expertsystem/data.py
  tests/unit/data/__init__.py
  tests/unit/data/test_particle.py
  tests/unit/data/test_particle_collection.py
  tests/unit/data/test_states.py
  tests/unit/test_data.py
  tests/unit/test_topology.py
  tox.ini
Labels: 💡 Enhancement, 🖱️ DX

#264 docs!: add interactive examples page
  .vscode/settings.json
  doc/.gitignore
  doc/conf.py
  doc/contribute.rst
  doc/index.rst
  doc/interactive.rst
  doc/tox.ini
  doc/usage.rst
  setup.cfg
Labels: 📝 Docs

#262 refactor: remove dicts in determine_node_settings
  expertsystem/state/particle.py
  expertsystem/topology.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_system_control.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#263 refactor: convert to dict after int. settings
  expertsystem/ui/__init__.py
Labels: 🔨 Maintenance

#269 refactor: split state.particle module
  examples/particles.ipynb
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/data.py
  expertsystem/io/xml/_dump.py
  expertsystem/nested_dicts.py
  expertsystem/state/__init__.py
  expertsystem/state/propagation.py
  expertsystem/state/properties.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/state/test_graph_combinatorics.py
  tests/unit/ui/test_system_control.py
  tox.ini
Labels: 🔨 Maintenance

#271 feat: improve Parity class
  expertsystem/data.py
  tests/unit/test_data.py
Labels: Bug, 💡 Enhancement

#270 feat: implement get_intermediate_states
  examples/quickstart.ipynb
  expertsystem/data.py
  expertsystem/ui/__init__.py
  tests/unit/test_data.py
  tests/unit/test_ui.py
Labels: 💡 Enhancement, 📝 Docs

#276 feat: add type hints amplitude module
  expertsystem/amplitude/abstract_generator.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/state/properties.py
  setup.cfg
Labels: 💡 Enhancement, 🖱️ DX

#277 chore: use python-constraint PyPI package
  .vscode/settings.json
  cspell.json
  doc/.gitignore
  doc/conf.py
  expertsystem/solvers/__init__.py
  expertsystem/solvers/constraint/__init__.py
  expertsystem/solvers/constraint/compat.py
  expertsystem/solvers/constraint/tox.ini
  expertsystem/solvers/constraint/version.py
  expertsystem/state/propagation.py
  pyrightconfig.json
  setup.cfg
  tox.ini
Labels: 🔨 Maintenance

#278 refactor!: simplify Propagator/Solver interface
  examples/quickstart.ipynb
  examples/visualization.ipynb
  expertsystem/data.py
  expertsystem/nested_dicts.py
  expertsystem/state/conservation_rules.py
  expertsystem/state/propagation.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  setup.cfg
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_jpsi_to_gamma_pi0_pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/conftest.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/ui/test_system_control.py
Labels: 🔨 Maintenance

#273 ci: implement doc8 check
  .pre-commit-config.yaml
  doc/contribute.rst
  doc/index.rst
  setup.cfg
Labels: 🖱️ DX

#279 ci: upgrade to pytest 6.1.0
  setup.cfg
Labels: 🖱️ DX

#280 chore!: reorganize code for new subpackage solving
  doc/index.rst
  expertsystem/data.py
  expertsystem/solving/__init__.py
  expertsystem/solving/conservation_rules.py
  expertsystem/state/__init__.py
  expertsystem/state/properties.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  tests/channels/test_nbody_reactions.py
  tests/unit/state/conservation_rules/test_additive_qn.py
  tests/unit/state/conservation_rules/test_c_parity.py
  tests/unit/state/conservation_rules/test_g_parity.py
  tests/unit/state/conservation_rules/test_ls_coupling.py
  tests/unit/state/conservation_rules/test_mass.py
  tests/unit/state/conservation_rules/test_spin.py
Labels: 🔨 Maintenance
