Repository ComPWA/expertsystem, pull requests merged in 2020-07, with the labels that each got.

#94 ci: simplify cspell set-up
  cspell.json
  doc/adr/0000-use-markdown-architectural-decision-records.md
  doc/contribute.rst
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#95 ci: fix missing Prettier hard-wrap config
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .prettierrc
  README.md
  cspell.json
  doc/adr/0000-use-markdown-architectural-decision-records.md
  doc/adr/template.md
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#96 ci!: ignore mypy expertsystem
  .pylintrc
  .vscode/settings.json
  cspell.json
  examples/python/jpsi_to_pipipi.py
  tests/particle/__init__.py
  tox.ini
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#97 ci: improve tox usage with more specific jobs
  .travis.yml
  doc/contribute.rst
  tox.ini
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Medium

#98 style!: fix all cspell errors
  .travis.yml
  cspell.json
  doc/adr.rst
  doc/index.rst
  doc/install/install.rst
  examples/jupyter/QuickStart.ipynb
  examples/python/JPsiToGammaPi0Pi0.xml
  examples/python/jpsi_to_pipipi.py
  expertsystem/amplitude/__init__.py
  expertsystem/amplitude/abstract_generator.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/state/__init__.py
  expertsystem/state/conservation_rules.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/topology/__init__.py
  expertsystem/topology/topology_builder.py
  expertsystem/ui/default_settings.py
  expertsystem/ui/system_control.py
  particle_list.xml
  particle_list.yml
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/canonical_formalism/test_ls_coupling.py
  tests/channels/test_d0_to_kskpkm.py
  tests/channels/test_jpsi_to_gammapi0pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0d0barpi0pi0.py
  tests/conservation_laws/test_cparity.py
  tests/conservation_laws/test_gparity.py
  tests/conservation_laws/test_mass.py
  tests/conservation_laws/test_spin.py
  tests/topology_builder/test_simplestatebuilder.py
Labels: :bulb: DX, :bulb: Maintenance, :clock2: Easy, :exclamation: Follow-up, :warning: Medium

#101 chore: remove Python examples
  examples/python/D0ToKs0KpKm.xml
  examples/python/JPsiToGammaPi0Pi0.xml
  examples/python/epem_to_chicpipi.py
  examples/python/epem_to_d0d0barpipi.py
  examples/python/jpsi_to_pipipi.py
Labels: :bulb: Maintenance, :clock1: Trivial, :exclamation: Follow-up, :warning: Medium

#99 refactor: add XML root tag
  .vscode/launch.json
  cspell.json
  expertsystem/amplitude/helicity_decay.py
  expertsystem/state/particle.py
  particle_list.xml
  tests/particle/test_read_write.py
  tox.ini
Labels: :bulb: Maintenance, :clock2: Easy, :exclamation: Follow-up, :warning: Medium, Bug

#104 refactor: capitalize globals
  expertsystem/state/particle.py
  expertsystem/ui/default_settings.py
  expertsystem/ui/system_control.py
  tests/particle/test_read_write.py
  tox.ini
Labels: :bulb: Maintenance, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#105 refactor: remove SYSTEM_SEARCH_PATHS
  .pylintrc
  expertsystem/ui/default_settings.py
  expertsystem/ui/system_control.py
Labels: :bulb: Maintenance, :clock1: Trivial, :warning: Low

#106 feat: add check on formalism type
  expertsystem/ui/system_control.py
Labels: :bulb: Enhancement, :clock1: Trivial, :warning: Low, Bug

#107 ci: speed up tox further
  tox.ini
Labels: :bulb: DX, :clock1: Trivial, :warning: Low

#100 feat!: add ParticleCollection structures
  .vscode/settings.json
  cspell.json
  doc/contribute.rst
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/data.py
  expertsystem/io/__init__.py
  expertsystem/io/_yaml/__init__.py
  expertsystem/io/_yaml/_build.py
  expertsystem/io/_yaml/_dump.py
  expertsystem/io/_yaml/validation.py
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  expertsystem/schemas/README.md
  expertsystem/schemas/yaml-particle-list.json
  expertsystem/state/conservation_rules.py
  expertsystem/state/particle.py
  expertsystem/ui/default_settings.py
  setup.cfg
  tests/amplitude/expected_recipe.yml
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/conservation_laws/test_cparity.py
  tests/conservation_laws/test_gparity.py
  tests/data/__init__.py
  tests/data/test_particle.py
  tests/io/__init__.py
  tests/io/test_yaml.py
  tox.ini
Labels: :bulb: Enhancement, :clock3: Medium, :exclamation: PR-series, :warning: High

#109 feat: implement xml <--> ParticleCollection
  .vscode/settings.json
  README.md
  cspell.json
  expertsystem/__init__.py
  expertsystem/io/__init__.py
  expertsystem/io/_xml/__init__.py
  expertsystem/io/_xml/_build.py
  expertsystem/io/_xml/_dump.py
  expertsystem/io/_xml/validation.py
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  expertsystem/schemas/xml/README.md
  expertsystem/schemas/xml/particle.json
  expertsystem/schemas/xml/particle_list.xml.json
  expertsystem/ui/system_control.py
  setup.cfg
  tests/io/test_internal_dict.py
  tests/io/test_particle_collection.py
  tests/io/test_yaml.py
  tests/particle/__init__.py
  tests/particle/test_read_write.py
Labels: :bulb: Enhancement, :bulb: Maintenance, :clock3: Medium, :exclamation: PR-series, :warning: High

#113 build!: implement setuptools-scm
  .github/ISSUE_TEMPLATE/feature_request.md
  .gitignore
  .prettierrc
  doc/adr/0000-use-markdown-architectural-decision-records.md
  doc/contribute.rst
  doc/install.rst
  environment.yml
  expertsystem/schemas/README.md
  expertsystem/schemas/xml/README.md
  pyproject.toml
  setup.cfg
Labels: :bulb: DX, :clock2: Easy, :warning: Medium

#112 fix: parameter linking and deterministic par names
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  cspell.json
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/amplitude/abstract_generator.py
  expertsystem/amplitude/canonical_decay.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/io/xml/__init__.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/xml/validation.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  expertsystem/io/yaml/validation.py
  expertsystem/schemas/xml/README.md
  expertsystem/schemas/xml/particle-list.json
  expertsystem/schemas/xml/particle.json
  expertsystem/schemas/yaml/amplitude-model.json
  expertsystem/schemas/yaml/particle-list.json
  setup.cfg
  tests/amplitude/test_parity_prefactor.py
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/io/test_particle_collection.py
Labels: :clock2: Easy, :warning: High, Bug

#114 ci: fix setuptools-scm deploy
  .travis.yml
  pyproject.toml
  setup.cfg
  setup.py
Labels: :clock1: Trivial, :warning: High, Bug

#115 fix: add copy button, faulty links, and doc8
  .travis.yml
  CONTRIBUTING.md
  doc/conf.py
  doc/contribute.rst
  pyproject.toml
  setup.cfg
Labels: :bulb: DX, :bulb: Docs, :clock1: Trivial, :warning: Medium

#116 docs: add Binder for QuickStart
  README.md
  doc/index.rst
  doc/usage.rst
  examples/quick_start.ipynb
Labels: :bulb: Docs, :clock1: Trivial, :warning: Medium

#117 docs: git clone over HTTP
  doc/contribute.rst
  doc/install.rst
Labels: :bulb: Docs, :clock1: Trivial, :warning: Low

#118 feat: serialize particle.DATABASE from/to YAML
  .gitignore
  .vscode/settings.json
  README.md
  cspell.json
  doc/conf.py
  doc/index.rst
  doc/usage.rst
  examples/additional_particles.yml
  examples/particles.ipynb
  examples/quickstart.ipynb
  expertsystem/state/particle.py
  expertsystem/ui/system_control.py
  tests/amplitude/test_parity_prefactor.py
  tests/state/__init__.py
  tests/state/conservation_rules/__init__.py
  tests/state/conservation_rules/test_cparity.py
  tests/state/conservation_rules/test_gparity.py
  tests/state/conservation_rules/test_mass.py
  tests/state/conservation_rules/test_spin.py
  tests/state/test_particle.py
Labels: :bulb: Docs, :bulb: Enhancement, :clock2: Easy, :warning: High

#120 refactor!: hide UI implementation details
  examples/particles.ipynb
  examples/quickstart.ipynb
  expertsystem/state/particle.py
  expertsystem/ui/__init__.py
  expertsystem/ui/_default_settings.py
  expertsystem/ui/_system_control.py
  tests/amplitude/test_parity_prefactor.py
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/canonical_formalism/test_ls_coupling.py
  tests/channels/test_d0_to_kskpkm.py
  tests/channels/test_jpsi_to_gammapi0pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0d0barpi0pi0.py
  tests/state/test_particle.py
  tests/ui/test_systemcontrol.py
  tox.ini
Labels: :bulb: Maintenance, :clock3: Medium, :warning: Medium

#121 feat: add write amplitude model from STM
  examples/quickstart.ipynb
  expertsystem/ui/__init__.py
  tests/amplitude/test_parity_prefactor.py
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/canonical_formalism/test_ls_coupling.py
  tests/channels/test_d0_to_kskpkm.py
  tests/channels/test_jpsi_to_gammapi0pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0d0barpi0pi0.py
  tests/ui/test_systemcontrol.py
Labels: :bulb: Enhancement, :clock2: Easy, :warning: Medium

#110 refactor!: ParticleCollection -> particle.DATABASE
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/amplitude/helicity_decay.py
  expertsystem/data.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  expertsystem/particle_list.xml
  expertsystem/schemas/yaml/particle-list.json
  expertsystem/state/particle.py
  tests/amplitude/expected_recipe.yml
  tests/amplitude/test_yaml_helicity.py
  tests/io/test_particle_collection.py
  tests/state/test_particle.py
Labels: :bulb: Enhancement, :clock4: Hard, :warning: High

#125 refactor!: remove MeasuredValue
  .gitignore
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/data.py
  expertsystem/io/xml/_build.py
  expertsystem/io/xml/_dump.py
  expertsystem/io/yaml/_build.py
  expertsystem/io/yaml/_dump.py
  expertsystem/particle_list.xml
  expertsystem/particle_list.yml
  expertsystem/schemas/yaml/particle-list.json
  tests/.gitignore
  tests/amplitude/expected_recipe.yml
  tests/data/test_particle.py
  tests/io/test_particle_collection.py
Labels: :bulb: Maintenance, :clock2: Easy, :warning: Medium

#139 refactor: merge data and particle Spin classes
  expertsystem/amplitude/canonical_decay.py
  expertsystem/data.py
  expertsystem/state/conservation_rules.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  tests/canonical_formalism/test_ls_coupling.py
  tests/state/conservation_rules/test_cparity.py
  tests/state/conservation_rules/test_gparity.py
  tests/state/conservation_rules/test_spin.py
Labels: :bulb: Maintenance, :clock2: Easy, :exclamation: PR-series, :warning: High
