Repository ComPWA/expertsystem, pull requests merged in 2020-06, with the labels that each got.

#48 adr: initialize architectual design records
  doc/adr/0000-use-markdown-architectural-decision-records.md
  doc/adr/index.rst
  doc/adr/template.md
  doc/conf.py
  doc/index.rst
  doc/requirements.txt
Labels: Priority: Medium, Type: Maintenance, documentation

#63 ci: enforce nbstripout over all notebooks
  .travis.yml
  examples/jupyter/QuickStart.ipynb
Labels: Priority: Low, Type: Maintenance

#61 ci: run pytest from root + add py38 job
  .travis.yml
Labels: Priority: Medium, Type: Maintenance

#59 feat: add helicity amplity recipe to YAML adapter
  .travis.yml
  examples/jupyter/QuickStart.ipynb
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/amplitude/canonicaldecay.py
  expertsystem/amplitude/helicitydecay.py
  tests/amplitude/__init__.py
  tests/amplitude/expected_recipe.yml
  tests/amplitude/test_yaml_recipe.py
  tests/channels/test_d0_to_kskpkm.py
  tests/channels/test_jpsi_to_gammapi0pi0.py
  tests/channels/test_y_to_d0d0barpi0pi0.py
Labels: Priority: High, Type: Enhancement

#52 ci: add issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/adr_pull_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Priority: Medium, Type: Maintenance

#51 doc: define purpose of the PWA Expert System
  README.md
  doc/index.rst
  setup.py
Labels: Priority: High, documentation

#71 feat: add YAML adapter canonical amplitude
  examples/jupyter/QuickStart.ipynb
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/amplitude/canonicaldecay.py
  pytest.ini
  setup.py
  tests/amplitude/test_yaml_canonical.py
  tests/amplitude/test_yaml_helicity.py
  tests/channels/test_y_to_d0d0barpi0pi0.py
Labels: Priority: Medium, Type: Enhancement

#75 docs: add heading Quickstart Step 1.4
  examples/jupyter/QuickStart.ipynb
Labels: :bulb: Docs, :clock1: Trivial, :warning: Low

#78 ci!: add and enforce Prettier formatting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .pre-commit-config.yaml
  .travis.yml
  .vscode/settings.json
  README.md
  doc/_templates/genindex.html
  doc/_templates/layout.html
  doc/adr/0000-use-markdown-architectural-decision-records.md
  doc/adr/template.md
Labels: :bulb: DX, :clock2: Easy, :exclamation: Follow-up, :warning: Low

#79 ci: add and enforce rstcheck
  .pre-commit-config.yaml
  .travis.yml
  .vscode/settings.json
  doc/install/install.rst
  doc/install/virtual-environment.rst
  requirements-dev.txt
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#80 refactor: switch to Enum class syntax
  examples/python/JPsiToPi0PipPim.py
  expertsystem/amplitude/helicitydecay.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/ui/system_control.py
  tests/canonical_formalism/test_ls_coupling.py
  tests/particle/test_read_write.py
  tests/ui/test_systemcontrol.py
Labels: :bulb: DX, :bulb: Maintenance, :clock1: Trivial, :warning: Low

#82 ci!: enforce pydocstyle check
  .vscode/settings.json
  doc/conf.py
  examples/python/EpEmToChicPipPim.py
  examples/python/EpEmToD0D0barPipPim.py
  examples/python/JPsiToPi0PipPim.py
  expertsystem/__init__.py
  expertsystem/amplitude/__init__.py
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/amplitude/abstractgenerator.py
  expertsystem/amplitude/canonicaldecay.py
  expertsystem/amplitude/helicitydecay.py
  expertsystem/solvers/__init__.py
  expertsystem/solvers/constraint/__init__.py
  expertsystem/solvers/constraint/tox.ini
  expertsystem/state/__init__.py
  expertsystem/state/conservationrules.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/topology/__init__.py
  expertsystem/topology/graph.py
  expertsystem/topology/topologybuilder.py
  expertsystem/ui/__init__.py
  expertsystem/ui/default_settings.py
  expertsystem/ui/system_control.py
  requirements-dev.txt
  setup.py
  tests/tox.ini
  tox.ini
Labels: :bulb: DX, :clock2: Easy, :exclamation: Follow-up, :warning: Low

#83 ci: run pytest and pytest-cov from root dir
  .travis.yml
  .vscode/settings.json
  doc/contribute.rst
  doc/install/install.rst
  pytest.ini
  tests/.coveragerc
  tox.ini
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#84 ci!: set up tox test environments
  .gitignore
  .travis.yml
  doc/contribute.rst
  doc/usage.rst
  tox.ini
Labels: :bulb: DX, :clock2: Easy, :exclamation: Follow-up, :warning: Medium

#85 ci: add more pre-commit hooks
  .pre-commit-config.yaml
  tox.ini
Labels: :bulb: DX, :clock1: Trivial, :exclamation: Follow-up, :warning: Low

#86 ci!: fix and enforce flake8 check
  examples/python/epem_to_chicpipi.py
  examples/python/epem_to_d0d0barpipi.py
  examples/python/jpsi_to_pipipi.py
  expertsystem/amplitude/canonicaldecay.py
  expertsystem/amplitude/helicitydecay.py
  expertsystem/state/conservationrules.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/topology/topologybuilder.py
  expertsystem/ui/default_settings.py
  expertsystem/ui/system_control.py
  tox.ini
Labels: :bulb: DX, :clock2: Easy, :exclamation: Follow-up, :warning: Medium

#87 ci!: fix and enforce pylint check
  .pylintrc
  expertsystem/amplitude/_yaml_adapter.py
  expertsystem/amplitude/canonicaldecay.py
  expertsystem/amplitude/helicitydecay.py
  expertsystem/solvers/constraint/__init__.py
  expertsystem/solvers/constraint/compat.py
  expertsystem/solvers/constraint/version.py
  expertsystem/state/conservationrules.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/topology/graph.py
  expertsystem/ui/default_settings.py
  expertsystem/ui/system_control.py
  tests/amplitude/test_yaml_helicity.py
  tox.ini
Labels: :bulb: DX, :bulb: Maintenance, :clock2: Easy, :exclamation: Follow-up, :warning: Medium

#88 docs: update documentation
  README.md
  doc/adr.rst
  doc/contribute.rst
  doc/index.rst
  doc/install.rst
Labels: :bulb: Docs, :clock2: Easy, :warning: Medium

#89 ci: simplify tox style check using SKIP
  tox.ini
Labels: :bulb: DX, :clock1: Trivial, :warning: Low

#90 ci: add cspell support
  .editorconfig
  .pre-commit-config.yaml
  .prettierignore
  .travis.yml
  .vscode/settings.json
  cspell.json
  doc/contribute.rst
  setup.py
Labels: :bulb: DX, :clock2: Easy, :warning: Low
