Repository ComPWA/expertsystem, pull requests merged in 2020-11, with the labels that each got.

#361 docs: improve rendering of the examples
  doc/_templates/genindex.html
  doc/conf.py
  doc/interactive.rst
  doc/usage.ipynb
  doc/usage/workflow.ipynb
  setup.cfg
  src/expertsystem/__init__.py
  src/expertsystem/amplitude/canonical_decay.py
  src/expertsystem/particle.py
  src/expertsystem/reaction/__init__.py
  src/expertsystem/reaction/conservation_rules.py
  tox.ini
Labels: 📝 Docs

#362 docs!: switch to MyST-NB
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .markdownlint.json
  .vscode/extensions.json
  cspell.json
  doc/conf.py
  doc/contribute.rst
  doc/index.md
  doc/index.rst
  doc/interactive.ipynb
  doc/interactive.rst
  doc/usage.ipynb
  doc/usage/particles.ipynb
  doc/usage/visualization.ipynb
  doc/usage/workflow.ipynb
  setup.cfg
  tox.ini
Labels: 📝 Docs

#365 ci: upgrade dev tools
  .pre-commit-config.yaml
  .vscode/settings.json
  CONTRIBUTING.md
  README.md
  cspell.json
  docs/conf.py
  docs/develop.rst
  docs/index.md
  docs/install.rst
  docs/usage/particles.ipynb
  setup.cfg
  src/expertsystem/reaction/_system_control.py
  tests/__init__.py
  tests/channels/__init__.py
  tests/unit/__init__.py
  tests/unit/amplitude/__init__.py
  tests/unit/io/__init__.py
  tests/unit/reaction/__init__.py
  tests/unit/reaction/conservation_rules/__init__.py
Labels: 📝 Docs, 🖱️ DX

#370 fix: update tqdm, tensorwaves links, vscode pytest
  .vscode/settings.json
  README.md
  docs/conf.py
  docs/install.rst
  docs/mypy_badge.svg
  environment.yml
  src/expertsystem/reaction/__init__.py
Labels: Bug, 📝 Docs, 🖱️ DX

#371 fix: use defaultdict in convert_to_names
  docs/conf.py
  src/expertsystem/reaction/solving.py
Labels: Bug

#368 feat: support pure edge and node rules in solving
  docs/usage/workflow.ipynb
  src/expertsystem/reaction/__init__.py
  src/expertsystem/reaction/_default_settings.py
  src/expertsystem/reaction/argument_handling.py
  src/expertsystem/reaction/conservation_rules.py
  src/expertsystem/reaction/solving.py
  tests/channels/test_nbody_reactions.py
Labels: 💡 Enhancement

#373 feat: add reaction violation checker
  docs/interactive.ipynb
  src/expertsystem/__init__.py
  src/expertsystem/reaction/__init__.py
  src/expertsystem/reaction/solving.py
  tests/channels/test_nbody_reactions.py
  tests/unit/test_reaction.py
Labels: 💡 Enhancement, 🔨 Maintenance

#375 docs: upgrade to Sphinx Book Theme 0.39
  docs/conf.py
  docs/develop.rst
  docs/index.md
  setup.cfg
Labels: 📝 Docs

#376 fix: clebsch gordan helicity to canonical rule
  src/expertsystem/reaction/conservation_rules.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/reaction/conservation_rules/test_clebsch_gordan.py
  tests/unit/reaction/conservation_rules/test_spin.py
Labels: Bug

#378 fix: build wheel and fix deploy job
  .github/workflows/cd.yml
  pyproject.toml
Labels: Bug, 🖱️ DX

#379 ci: fix release to pypi upon (pre)release
  .github/workflows/cd.yml
Labels: Bug, 🖱️ DX

#381 test: add unit tests for all conservation rules
  cspell.json
  src/expertsystem/reaction/conservation_rules.py
  tests/unit/reaction/conservation_rules/test_gellmann_nishijima.py
  tests/unit/reaction/conservation_rules/test_helicity_conservation.py
  tests/unit/reaction/conservation_rules/test_identical_particle_symmetrization.py
  tests/unit/reaction/conservation_rules/test_parity_conservation.py
Labels: 💡 Enhancement

#391 docs!: outsource develop to PWA pages
  .gitignore
  CONTRIBUTING.md
  README.md
  docs/.gitignore
  docs/_static/favicon.ico
  docs/api.rst
  docs/conf.py
  docs/develop.rst
  docs/index.md
  docs/install.md
  docs/install.rst
  pyrightconfig.json
Labels: 📝 Docs

#392 build!: upgrade and reorganize dependencies
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  .pylintrc
  .vscode/settings.json
  commitlint.config.js
  cspell.json
  docs/conf.py
  setup.cfg
  tests/output/.gitignore
  tests/output/.gitkeep
  tox.ini
Labels: 🔨 Maintenance, 🖱️ DX

#395 fix: correctly dump Breit-Wigner
  docs/usage/workflow.ipynb
  src/expertsystem/io/_xml/_build.py
  src/expertsystem/io/_xml/_dump.py
  src/expertsystem/io/_yaml/_dump.py
  src/expertsystem/schemas/yaml/amplitude-model.json
  tests/unit/amplitude/expected_recipe.yml
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/conftest.py
Labels: Bug, 🔨 Maintenance

#396 docs: link API through reStructuredText links
  docs/interactive.ipynb
  docs/usage.ipynb
  docs/usage/particles.ipynb
  docs/usage/visualization.ipynb
  docs/usage/workflow.ipynb
Labels: 🖱️ DX

#398 ci: upgrade dependencies
  .reqs/doc.txt
  .reqs/sty.txt
  .reqs/test.txt
  requirements-dev.txt
  requirements.txt
  src/expertsystem/io/_pdg.py
  tests/unit/io/test_pdg.py
  tests/unit/test_particles.py
Labels: Bug, 🖱️ DX

#399 fix: broken RTD links and limit VSCode file scan
  .vscode/settings.json
  docs/usage/workflow.ipynb
Labels: Bug, 🖱️ DX
