Repository ComPWA/expertsystem, pull requests merged in 2020-05, with the labels that each got.

#20 docs: add description main module
  CONTRIBUTING.md
  expertsystem/__init__.py
  expertsystem/visualization/__init__.py
  expertsystem/visualization/graphvis.py
Labels: documentation

#21 test: clean up tests folder
  .travis.yml
  examples/python/D0ToKs0KpKm.xml
  examples/python/EpEmToChicPipPim.py
  examples/python/EpEmToD0D0barPipPim.py
  examples/python/JPsiToGammaPi0Pi0.xml
  examples/python/JPsiToPi0PipPim.py
  tests/.gitignore
  tests/angular-distribution-tests/D1ToD0PipPim/disabled_test_angular_dist.py
  tests/angular-distribution-tests/D1ToD0PipPim/model.xml
  tests/angular-distribution-tests/EpEmToDmD0Pip/disabled_test_angular_dist.py
  tests/angular-distribution-tests/EpEmToDmD0Pip/model.xml
  tests/angular-distribution-tests/distributioncomparison.py
  tests/canonical-formalism/test_LSCoupling.py
  tests/channels/test_D0ToKsKpKm.py
  tests/channels/test_JPsiToGammaPi0Pi0Decay.py
  tests/channels/test_YToD0D0barPi0Pi0.py
  tests/channels/test_nbody_reactions.py
  tests/conservation-laws/test_cparity.py
  tests/conservation-laws/test_gparity.py
  tests/conservation-laws/test_mass.py
  tests/conservation-laws/test_spin.py
  tests/pytest.ini
  tests/topology-builder/test_simplestatebuilder.py
  tests/ui/test_systemcontrol.py
  tox.ini
Labels: Priority: Medium, Type: Maintenance

#29 docs: improve README, add pre-commit badge
  README.md
  doc/index.rst
Labels: Priority: Low, documentation

#28 ci: add pydocstyle check
  .pre-commit-config.yaml
  requirements-dev.txt
  tests/.coveragerc
  tox.ini
Labels: Priority: Medium, Type: Maintenance, documentation

#32 feat: add yaml particle list
  .pre-commit-config.yaml
  particle_list.xml
  particle_list.yml
  setup.py
Labels: Type: Maintenance

#35 refactor!: remove XML attributes
  .pylintrc
  examples/python/EpEmToChicPipPim.py
  examples/python/EpEmToD0D0barPipPim.py
  examples/python/JPsiToPi0PipPim.py
  expertsystem/amplitude/canonicaldecay.py
  expertsystem/amplitude/helicitydecay.py
  expertsystem/state/particle.py
  expertsystem/state/propagation.py
  expertsystem/ui/default_settings.py
  expertsystem/ui/system_control.py
  particle_list.xml
  requirements-dev.txt
  tests/canonical-formalism/test_LSCoupling.py
  tests/channels/test_D0ToKsKpKm.py
  tests/channels/test_JPsiToGammaPi0Pi0Decay.py
  tests/particle/test_read_write.py
  tests/ui/test_systemcontrol.py
  tox.ini
Labels: Priority: Medium, Type: Maintenance

#36 feat: add yaml support for particle list
  expertsystem/state/particle.py
  requirements.txt
  tests/.gitignore
  tests/particle/test_read_write.py
Labels: Type: Maintenance

#38 build: drop python support below 3.6
  .gitignore
  .travis.yml
  doc/contribute.rst
  environment.yml
  expertsystem/__init__.py
  setup.py
Labels: Priority: Medium, Type: Maintenance

#39 style: fix linting issues in tests
  tests/__init__.py
  tests/canonical_formalism/__init__.py
  tests/canonical_formalism/test_ls_coupling.py
  tests/channels/__init__.py
  tests/channels/test_d0_to_kskpkm.py
  tests/channels/test_jpsi_to_gammapi0pi0.py
  tests/channels/test_nbody_reactions.py
  tests/channels/test_y_to_d0d0barpi0pi0.py
  tests/conservation_laws/__init__.py
  tests/conservation_laws/test_cparity.py
  tests/conservation_laws/test_gparity.py
  tests/conservation_laws/test_mass.py
  tests/conservation_laws/test_spin.py
  tests/topology-builder/test_simplestatebuilder.py
  tests/topology_builder/__init__.py
  tests/topology_builder/test_simplestatebuilder.py
  tests/ui/__init__.py
  tests/ui/test_systemcontrol.py
  tox.ini
Labels: Priority: Low, Type: Maintenance

#34 feat: add Quickstart notebook
  .gitignore
  .travis.yml
  doc/.gitignore
  doc/conf.py
  doc/index.rst
  doc/requirements.txt
  doc/usage.rst
  examples/jupyter/QuickStart.ipynb
Labels: Priority: High, documentation
