Repository ComPWA/expertsystem, pull requests merged in 2021-01, with the labels that each got.

#416 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
Labels: 🔨 Maintenance, 🖱️ DX

#420 ci: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 🖱️ DX

#417 fix: officially remove top NormalizedIntensity
  src/expertsystem/amplitude/helicity_decay.py
  tests/channels/test_d0_to_ks_kp_km.py
  tests/channels/test_y_to_d0_d0bar_pi0_pi0.py
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
Labels: Bug, 💡 Enhancement

#421 fix: decouple parity violating amplitudes
  src/expertsystem/amplitude/helicity_decay.py
  tests/unit/amplitude/test_parity_prefactor.py
Labels: Bug

#423 fix: add Interface label to PR linting
  .github/workflows/pr-linting.yml
Labels: Bug, 🖱️ DX

#425 refactor!: remove XML support
  .editorconfig
  .gitignore
  .vscode/settings.json
  README.md
  cspell.json
  docs/usage/particles.ipynb
  docs/usage/workflow.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  setup.cfg
  src/expertsystem/io/__init__.py
  src/expertsystem/io/_xml/__init__.py
  src/expertsystem/io/_xml/_build.py
  src/expertsystem/io/_xml/_dump.py
  src/expertsystem/io/_xml/validation.py
  src/expertsystem/io/_yaml/validation.py
  src/expertsystem/schemas/amplitude-model.json
  src/expertsystem/schemas/particle-list.json
  src/expertsystem/schemas/xml/README.md
  src/expertsystem/schemas/xml/particle-list.json
  src/expertsystem/schemas/xml/particle.json
  tests/channels/test_d0_to_ks_kp_km.py
  tests/unit/amplitude/test_io.py
  tests/unit/amplitude/test_parity_prefactor.py
  tests/unit/io/test_particle_list.py
  tests/unit/io/test_xml.py
Labels: ⚠️ Interface

#427 feat: implement FitParameters repr and eq
  docs/conf.py
  docs/index.md
  src/expertsystem/amplitude/model.py
  tests/unit/amplitude/test_model.py
Labels: 💡 Feature

#426 feat!: implement io.asdict and io.fromdict
  docs/usage/particles.ipynb
  src/expertsystem/io/__init__.py
  src/expertsystem/io/_dict/__init__.py
  src/expertsystem/io/_dict/_build.py
  src/expertsystem/io/_dict/_dump.py
  src/expertsystem/io/_dict/_validate.py
  tests/unit/amplitude/test_yaml_canonical.py
  tests/unit/amplitude/test_yaml_helicity.py
  tests/unit/io/expected_recipe.yml
  tests/unit/io/test_dict.py
  tests/unit/io/test_dot.py
  tests/unit/io/test_particle_list.py
  tests/unit/test_io.py
  tests/unit/test_particle.py
Labels: Bug, 💡 Feature, 🖱️ DX

#428 refactor!: merge load functions
  .gitignore
  README.md
  docs/usage/particles.ipynb
  docs/usage/workflow.ipynb
  src/expertsystem/io/__init__.py
  src/expertsystem/io/_dict/__init__.py
  src/expertsystem/io/_dict/build.py
  src/expertsystem/io/_dict/dump.py
  src/expertsystem/io/_dict/validate.py
  src/expertsystem/reaction/__init__.py
  tests/unit/io/test_dict.py
  tests/unit/test_io.py
Labels: ⚠️ Interface, 💡 Feature

#429 ci: validate JSON files with schemas in VSCode
  .vscode/settings.json
  tests/unit/io/expected_recipe.yml
  tests/unit/io/test_dict.py
Labels: 🖱️ DX

#430 refactor: remove Type key from Parameters section
  src/expertsystem/io/_dict/dump.py
  src/expertsystem/schemas/amplitude-model.json
  tests/unit/io/expected_recipe.yml
Labels: ⚠️ Interface

#431 fix: avoid validating when building dict
  src/expertsystem/io/_dict/dump.py
  tests/unit/io/test_dict.py
  tests/unit/test_io.py
Labels: Bug

#432 refactor: make FitParameter.value required
  src/expertsystem/amplitude/model.py
  tests/unit/amplitude/test_model.py
Labels: ⚠️ Interface

#433 ci: run mypy on src folder
  tox.ini
Labels: Bug, 🖱️ DX

#434 refactor: make ParticleDynamics mutable
  src/expertsystem/amplitude/model.py
  src/expertsystem/io/_dict/build.py
  tests/unit/io/test_dict.py
Labels: Bug, ⚠️ Interface

#438 ci: pin Pyright to version 1.1.99
  .github/workflows/ci.yml
Labels: Bug

#435 ci: change PR author to GitHub bot
  .github/workflows/requirements-cron.yml
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
Labels: 🖱️ DX

#436 refactor!: use attr.asdict in io module
  docs/usage/additional_particles.yml
  src/expertsystem/additional_particle_definitions.yml
  src/expertsystem/amplitude/helicity_decay.py
  src/expertsystem/amplitude/model.py
  src/expertsystem/io/__init__.py
  src/expertsystem/io/_dict/build.py
  src/expertsystem/io/_dict/dump.py
  src/expertsystem/io/_dict/validate.py
  src/expertsystem/schemas/amplitude-model.json
  src/expertsystem/schemas/particle-list.json
  tests/unit/amplitude/test_model.py
  tests/unit/io/expected_recipe.yml
  tests/unit/io/test_dict.py
Labels: ⚠️ Interface, 🖱️ DX

#439 refactor: rename pole to real and imag
  src/expertsystem/amplitude/model.py
  src/expertsystem/io/_dict/build.py
  tests/unit/io/expected_recipe.yml
Labels: ⚠️ Interface

#444 fix: set minimal version for mypy for attrs
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/requirements-sty.in
Labels: 🖱️ DX

#446 fix: install sphinx-autobuild through dev reqs
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/requirements-dev.in
  reqs/requirements-doc.in
  tox.ini
Labels: Bug, 🖱️ DX

#448 ci: run pytest on all cores
  .github/workflows/ci.yml
Labels: 🖱️ DX

#449 feat: add Particle.latex tag
  docs/usage/particles.ipynb
  src/expertsystem/io/_pdg.py
  src/expertsystem/particle.py
  src/expertsystem/schemas/particle-list.json
  tests/unit/io/expected_recipe.yml
  tests/unit/test_particle.py
Labels: 💡 Feature

#450 ci: upgrade developer dependencies
  .pre-commit-config.yaml
  .pylintrc
  cspell.json
  labels.toml
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.9/requirements-dev.txt
  reqs/3.9/requirements-doc.txt
  reqs/3.9/requirements-sty.txt
  reqs/3.9/requirements-test.txt
  tox.ini
Labels: 🖱️ DX

#451 ci!: remove reStructuredText support
  .pre-commit-config.yaml
  .vscode/extensions.json
  .vscode/settings.json
  commitlint.config.js
  docs/adr.md
  docs/adr.rst
  docs/conf.py
  docs/index.md
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.9/requirements-dev.txt
  reqs/3.9/requirements-sty.txt
  reqs/requirements-sty.in
  setup.cfg
Labels: 🖱️ DX

#452 docs: remove module visualization
  cspell.json
  docs/conf.py
  reqs/3.6/requirements-doc.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.9/requirements-doc.txt
  reqs/requirements-dev.in
  reqs/requirements-doc.in
  tox.ini
Labels: 📝 Docs, 🖱️ DX

#453 refactor: simplify and freeze Kinematics class
  src/expertsystem/amplitude/helicity_decay.py
  src/expertsystem/amplitude/model.py
  src/expertsystem/io/_dict/build.py
  src/expertsystem/io/_dict/dump.py
  tests/unit/amplitude/test_model.py
  tests/unit/io/test_dict.py
Labels: ⚠️ Interface

#445 adr: decide on amplitude model structure
  cspell.json
  docs/adr/000-adrs.md
  docs/adr/001-amplitude-model.md
  docs/adr/examples/001/operators.ipynb
  docs/adr/examples/001/parameter_container.py
  docs/adr/examples/001/sympy.ipynb
  docs/adr/template.md
  docs/conf.py
Labels: 📝 Docs

#455 ci: run CI again on draft PR
  .github/workflows/ci.yml
  .github/workflows/linkcheck.yml
  .github/workflows/requirements-pr.yml
Labels: 🖱️ DX

#457 ci: upgrade developer dependencies
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.6/requirements.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.7/requirements.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.8/requirements.txt
  reqs/3.9/requirements-dev.txt
  reqs/3.9/requirements-doc.txt
  reqs/3.9/requirements-sty.txt
  reqs/3.9/requirements-test.txt
  reqs/3.9/requirements.txt
Labels: 🖱️ DX

#462 ci: activate color in tox sphinx-autobuild
  cspell.json
  tox.ini
Labels: 🖱️ DX

#463 build: upgrade myst-parser/myst-nb
  docs/conf.py
  reqs/3.6/requirements-dev.txt
  reqs/3.6/requirements-doc.txt
  reqs/3.6/requirements-sty.txt
  reqs/3.6/requirements-test.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.7/requirements-doc.txt
  reqs/3.7/requirements-sty.txt
  reqs/3.7/requirements-test.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.8/requirements-doc.txt
  reqs/3.8/requirements-sty.txt
  reqs/3.8/requirements-test.txt
  reqs/3.9/requirements-dev.txt
  reqs/3.9/requirements-doc.txt
  reqs/3.9/requirements-sty.txt
  reqs/3.9/requirements-test.txt
  reqs/requirements-doc.in
Labels: 🔨 Maintenance, 🖱️ DX

#464 chore: clean up ADR folder and template
  cspell.json
  docs/adr/000.md
  docs/adr/001.md
  docs/adr/001/operators.ipynb
  docs/adr/001/parameter_container.py
  docs/adr/001/sympy.ipynb
  docs/adr/template.md
  docs/conf.py
Labels: 🖱️ DX

#465 fix: add math-dollar and other myst extensions
  docs/conf.py
Labels: Bug

#466 ci: format jupyter notebooks with nbqa
  .pre-commit-config.yaml
  docs/adr/001/operators.ipynb
  docs/adr/001/sympy.ipynb
  docs/interactive.ipynb
  docs/usage/particles.ipynb
  docs/usage/visualization.ipynb
  docs/usage/workflow.ipynb
  reqs/3.6/requirements-dev.txt
  reqs/3.7/requirements-dev.txt
  reqs/3.8/requirements-dev.txt
  reqs/3.9/requirements-dev.txt
  reqs/requirements-dev.in
Labels: 🖱️ DX
